version: "3"

services:
    spark-master:
        image: snps/spark
        environment:
            - SPARK_WORKER_PORT=7001
        ports: 
            - "8080:8080"
            - "7077:7077"
        networks:
            - spark-cluster
        command: ["./keep_running.sh", "./spark-2.2.0-bin-hadoop2.7/sbin/start-master.sh"]
    spark-slave:
        image: snps/spark
        environment:
            - SPARK_WORKER_PORT=7001
        expose:
            - "7001"
        networks:
            - spark-cluster
        links:
            - spark-master
        depends_on:
            - spark-master
        command: ["./keep_running.sh", "./spark-2.2.0-bin-hadoop2.7/sbin/start-slave.sh", "spark://spark-master:7077"]
networks:
    spark-cluster:
